FROM node:16

# Setting up the environment variables
ARG REACT_APP_API_URL=https://smear-backend-avaa-smear-dev.rahtiapp.fi
ARG REACT_APP_METRICS_SCRIPT_URL
ENV REACT_APP_API_URL=$REACT_APP_API_URL
ENV REACT_APP_METRICS_SCRIPT_URL=$REACT_APP_METRICS_SCRIPT_URL

RUN apt update -y

# Install application
WORKDIR /app
COPY package.json .
COPY yarn.lock .

RUN yarn install

COPY . .

# User management
ARG DEVELOPER_UID=1001
ARG DEVELOPER_GID=1001

RUN groupadd -g $DEVELOPER_GID developer
RUN useradd -m -s /bin/bash -u $DEVELOPER_UID -g $DEVELOPER_GID developer

# Set locale
ENV LANG C.UTF-8

# Start application
EXPOSE 3000

CMD ["yarn", "start"]
